location_to_background_probabilities = {
    "village": {
        "commoner": 0.25,
        "fisherman": 0.15,
        "farmer": 0.20,
        "hermit": 0.10,
        "guard": 0.05,
        "mage": 0.05,
    },
    "fortified_settlement": {
        "guard": 0.30,
        "soldier": 0.25,
        "mage": 0.10,
        "noble": 0.05,
        "commoner": 0.15,
        "alchemist": 0.05,
    },
    "town": {
        "guard": 0.20,
        "commoner": 0.25,
        "merchant": 0.15,
        "mage": 0.05,
        "noble": 0.10,
        "adventurer": 0.10,
    },
    "mining_town": {
        "miner": 0.30,
        "smith": 0.15,
        "guard": 0.10,
        "merchant": 0.10,
        "commoner": 0.20,
        "adventurer": 0.05,
    },
    "city": {
        "noble": 0.15,
        "merchant": 0.20,
        "guard": 0.10,
        "mage": 0.10,
        "commoner": 0.25,
        "scholar": 0.05,
    },
    "grand_city": {
        "noble": 0.20,
        "mage": 0.15,
        "scholar": 0.10,
        "merchant": 0.20,
        "commoner": 0.15,
        "guard": 0.10,
    },
    "fishing_village": {
        "fisherman": 0.40,
        "commoner": 0.30,
        "merchant": 0.10,
        "guard": 0.05,
        "hermit": 0.05,
        "adventurer": 0.05,
    },
    "kwama_egg_mine": {
        "miner": 0.40,
        "guard": 0.20,
        "alchemist": 0.10,
        "commoner": 0.20,
        "mage": 0.10,
    },
    "imperial_fort": {
        "imperial_legionnaire": 0.40,
        "guard": 0.25,
        "mage": 0.10,
        "commoner": 0.15,
        "merchant": 0.10,
    },
    "daedric_shrine": {
        "daedra_worshipper": 0.40,
        "mage": 0.20,
        "hermit": 0.15,
        "necromancer": 0.15,
        "adventurer": 0.10,
    },
    "dunmer_stronghold": {
        "warrior": 0.30,
        "mage": 0.20,
        "noble": 0.20,
        "commoner": 0.20,
        "alchemist": 0.10,
    },
    "cave": {
        "bandit": 0.35,
        "hermit": 0.20,
        "smuggler": 0.20,
        "adventurer": 0.15,
        "necromancer": 0.10,
    },
    "telvanni_mage_tower": {
        "telvanni_mage": 0.40,
        "scholar": 0.25,
        "commoner": 0.15,
        "alchemist": 0.10,
        "guard": 0.10,
    },
    "ashlander_camp": {
        "ashlander": 0.40,
        "hunter": 0.25,
        "hermit": 0.15,
        "shaman": 0.10,
        "scout": 0.10,
    },
    "dwemer_ruin": {
        "adventurer": 0.30,
        "dwemer_researcher": 0.25,
        "bandit": 0.20,
        "mage": 0.15,
        "guard": 0.10,
    },
}