# morality - 0 to 10 (used to generate personality traits)
# intelligence - 0 to 10 (used to generate personality traits)
# courage - 0 to 10 (used to generate personality traits)

# talkativeness - 0 to 10 (length of conversation and its responses)
# extraversion - 0 to 10 (more reflective of oneself or outward oriented)
# patience - 0 to 10
# empathy - 0 to 10 (ability to read other people, in the context of this game - to detect personality traits of other characters)
# openness - 0 to 10 (readiness to share facts)

background_to_characteristics_probabilities = {
    "commoner": {
        "morality": {"mean": 5, "std": 2},
        "intelligence": {"mean": 4, "std": 2},
        "courage": {"mean": 4, "std": 2},
        "talkativeness": {"mean": 4, "std": 2},
        "extraversion": {"mean": 4, "std": 2},
        "patience": {"mean": 3, "std": 2},
        "empathy": {"mean": 4, "std": 2},
        "openness": {"mean": 4, "std": 2},
    },
    "guard": {
        "morality": {"mean": 7, "std": 2},
        "intelligence": {"mean": 5, "std": 2},
        "courage": {"mean": 7, "std": 2},
        "talkativeness": {"mean": 3, "std": 2},
        "extraversion": {"mean": 3, "std": 2},
        "patience": {"mean": 6, "std": 2},
        "empathy": {"mean": 3, "std": 2},
        "openness": {"mean": 3, "std": 2},
    },
    "mage": {
        "morality": {"mean": 7, "std": 2},
        "intelligence": {"mean": 10, "std": 2},
        "courage": {"mean": 5, "std": 2},
        "talkativeness": {"mean": 3, "std": 2},
        "extraversion": {"mean": 3, "std": 2},
        "patience": {"mean": 5, "std": 2},
        "empathy": {"mean": 4, "std": 2},
        "openness": {"mean": 3, "std": 2},
    },
    "necromancer": {
        "morality": {"mean": 2, "std": 2},
        "intelligence": {"mean": 10, "std": 2},
        "courage": {"mean": 5, "std": 2},
        "talkativeness": {"mean": 2, "std": 2},
        "extraversion": {"mean": 2, "std": 2},
        "patience": {"mean": 4, "std": 2},
        "empathy": {"mean": 2, "std": 2},
        "openness": {"mean": 2, "std": 2},
    },
    "telvanni_mage": {
        "morality": {"mean": 3, "std": 2},
        "intelligence": {"mean": 10, "std": 2},
        "courage": {"mean": 5, "std": 2},
        "talkativeness": {"mean": 2, "std": 2},
        "extraversion": {"mean": 2, "std": 2},
        "patience": {"mean": 4, "std": 2},
        "empathy": {"mean": 2, "std": 2},
        "openness": {"mean": 4, "std": 2},
    },
    "noble": {
        "morality": {"mean": 5, "std": 2},
        "intelligence": {"mean": 7, "std": 2},
        "courage": {"mean": 5, "std": 2},
        "talkativeness": {"mean": 4, "std": 2},
        "extraversion": {"mean": 5, "std": 2},
        "patience": {"mean": 4, "std": 2},
        "empathy": {"mean": 4, "std": 2},
        "openness": {"mean": 4, "std": 2},
    },
    "adventurer": {
        "morality": {"mean": 5, "std": 2},
        "intelligence": {"mean": 5, "std": 2},
        "courage": {"mean": 8, "std": 2},
        "talkativeness": {"mean": 5, "std": 2},
        "extraversion": {"mean": 5, "std": 2},
        "patience": {"mean": 3, "std": 2},
        "empathy": {"mean": 4, "std": 2},
        "openness": {"mean": 5, "std": 2},
    },
    "outlaw": {
        "morality": {"mean": 3, "std": 2},
        "intelligence": {"mean": 5, "std": 2},
        "courage": {"mean": 7, "std": 2},
        "talkativeness": {"mean": 4, "std": 2},
        "extraversion": {"mean": 4, "std": 2},
        "patience": {"mean": 2, "std": 2},
        "empathy": {"mean": 2, "std": 2},
        "openness": {"mean": 3, "std": 2},
    },
    "hermit": {
        "morality": {"mean": 7, "std": 2},
        "intelligence": {"mean": 7, "std": 2},
        "courage": {"mean": 5, "std": 2},
        "talkativeness": {"mean": 1, "std": 1},
        "extraversion": {"mean": 1, "std": 1},
        "patience": {"mean": 5, "std": 2},
        "empathy": {"mean": 2, "std": 1},
        "openness": {"mean": 1, "std": 1},
    },
    "ashlander": {
        "morality": {"mean": 5, "std": 2},
        "intelligence": {"mean": 5, "std": 2},
        "courage": {"mean": 7, "std": 2},
        "talkativeness": {"mean": 2, "std": 1},
        "extraversion": {"mean": 2, "std": 1},
        "patience": {"mean": 4, "std": 2},
        "empathy": {"mean": 3, "std": 1},
        "openness": {"mean": 2, "std": 1},
    },
    "sadrith_mora_scholar": {
        "morality": {"mean": 7, "std": 2},
        "intelligence": {"mean": 8, "std": 2},
        "courage": {"mean": 3, "std": 2},
        "talkativeness": {"mean": 4, "std": 2},
        "extraversion": {"mean": 2, "std": 1},
        "patience": {"mean": 5, "std": 2},
        "empathy": {"mean": 4, "std": 2},
        "openness": {"mean": 4, "std": 2},
    },
    "redoran_warrior": {
        "morality": {"mean": 7, "std": 2},
        "intelligence": {"mean": 5, "std": 2},
        "courage": {"mean": 8, "std": 2},
        "talkativeness": {"mean": 3, "std": 1},
        "extraversion": {"mean": 4, "std": 2},
        "patience": {"mean": 4, "std": 2},
        "empathy": {"mean": 3, "std": 1},
        "openness": {"mean": 3, "std": 1},
    },
    "hlaalu_trader": {
        "morality": {"mean": 5, "std": 2},
        "intelligence": {"mean": 7, "std": 2},
        "courage": {"mean": 5, "std": 2},
        "talkativeness": {"mean": 5, "std": 2},
        "extraversion": {"mean": 5, "std": 2},
        "patience": {"mean": 4, "std": 2},
        "empathy": {"mean": 4, "std": 2},
        "openness": {"mean": 5, "std": 2},
    },
    "balmora_citizen": {
        "morality": {"mean": 5, "std": 2},
        "intelligence": {"mean": 3, "std": 2},
        "courage": {"mean": 3, "std": 2},
        "talkativeness": {"mean": 4, "std": 2},
        "extraversion": {"mean": 4, "std": 2},
        "patience": {"mean": 4, "std": 2},
        "empathy": {"mean": 4, "std": 2},
        "openness": {"mean": 4, "std": 2},
    },
    "vivec_city_monk": {
        "morality": {"mean": 8, "std": 2},
        "intelligence": {"mean": 7, "std": 2},
        "courage": {"mean": 5, "std": 2},
        "talkativeness": {"mean": 2, "std": 1},
        "extraversion": {"mean": 2, "std": 1},
        "patience": {"mean": 5, "std": 2},
        "empathy": {"mean": 5, "std": 2},
        "openness": {"mean": 2, "std": 1},
    },
    "imperial_legionnaire": {
        "morality": {"mean": 5, "std": 2},
        "intelligence": {"mean": 5, "std": 2},
        "courage": {"mean": 7, "std": 2},
        "talkativeness": {"mean": 5, "std": 2},
        "extraversion": {"mean": 5, "std": 2},
        "patience": {"mean": 4, "std": 2},
        "empathy": {"mean": 4, "std": 2},
        "openness": {"mean": 5, "std": 2},
    },
    "dwemer_researcher": {
        "morality": {"mean": 5, "std": 2},
        "intelligence": {"mean": 7, "std": 2},
        "courage": {"mean": 4, "std": 2},
        "talkativeness": {"mean": 2, "std": 1},
        "extraversion": {"mean": 2, "std": 1},
        "patience": {"mean": 5, "std": 2},
        "empathy": {"mean": 5, "std": 2},
        "openness": {"mean": 2, "std": 1},
    },
    "morrowind_pilgrim": {
        "morality": {"mean": 6, "std": 2},
        "intelligence": {"mean": 5, "std": 2},
        "courage": {"mean": 5, "std": 2},
        "talkativeness": {"mean": 4, "std": 2},
        "extraversion": {"mean": 4, "std": 2},
        "patience": {"mean": 5, "std": 2},
        "empathy": {"mean": 4, "std": 2},
        "openness": {"mean": 4, "std": 2},
    },
    "ebony_mine_worker": {
        "morality": {"mean": 5, "std": 2},
        "intelligence": {"mean": 4, "std": 2},
        "courage": {"mean": 6, "std": 2},
        "talkativeness": {"mean": 2, "std": 2},
        "extraversion": {"mean": 2, "std": 2},
        "patience": {"mean": 4, "std": 2},
        "empathy": {"mean": 2, "std": 2},
        "openness": {"mean": 2, "std": 2},
    },
    "daedra_worshipper": {
        "morality": {"mean": 3, "std": 2},
        "intelligence": {"mean": 5, "std": 2},
        "courage": {"mean": 6, "std": 2},
        "talkativeness": {"mean": 5, "std": 2},
        "extraversion": {"mean": 5, "std": 2},
        "patience": {"mean": 2, "std": 2},
        "empathy": {"mean": 2, "std": 2},
        "openness": {"mean": 5, "std": 2},
    },
    "vampire_hunter": {
        "morality": {"mean": 5, "std": 2},
        "intelligence": {"mean": 6, "std": 2},
        "courage": {"mean": 7, "std": 2},
        "talkativeness": {"mean": 3, "std": 2},
        "extraversion": {"mean": 3, "std": 2},
        "patience": {"mean": 4, "std": 2},
        "empathy": {"mean": 4, "std": 2},
        "openness": {"mean": 4, "std": 2},
    },
    "buoyant_armiger": {
        "morality": {"mean": 7, "std": 2},
        "intelligence": {"mean": 7, "std": 2},
        "courage": {"mean": 8, "std": 2},
        "talkativeness": {"mean": 4, "std": 2},
        "extraversion": {"mean": 4, "std": 2},
        "patience": {"mean": 3, "std": 2},
        "empathy": {"mean": 3, "std": 2},
        "openness": {"mean": 4, "std": 2},
    },
    "silt_strider_operator": {
        "morality": {"mean": 5, "std": 2},
        "intelligence": {"mean": 4, "std": 2},
        "courage": {"mean": 5, "std": 2},
        "talkativeness": {"mean": 3, "std": 2},
        "extraversion": {"mean": 3, "std": 2},
        "patience": {"mean": 5, "std": 2},
        "empathy": {"mean": 2, "std": 2},
        "openness": {"mean": 3, "std": 2},
    },
    "mournhold_royalty": {
        "morality": {"mean": 7, "std": 2},
        "intelligence": {"mean": 7, "std": 2},
        "courage": {"mean": 5, "std": 2},
        "talkativeness": {"mean": 5, "std": 2},
        "extraversion": {"mean": 5, "std": 2},
        "patience": {"mean": 2, "std": 2},
        "empathy": {"mean": 2, "std": 2},
        "openness": {"mean": 5, "std": 2},
    },
    "fisherman": {
        "morality": {"mean": 5, "std": 2},
        "intelligence": {"mean": 4, "std": 2},
        "courage": {"mean": 5, "std": 2},
        "talkativeness": {"mean": 2, "std": 2},
        "extraversion": {"mean": 2, "std": 2},
        "patience": {"mean": 5, "std": 2},
        "empathy": {"mean": 3, "std": 2},
        "openness": {"mean": 2, "std": 2},
    },
    "alchemist": {
        "morality": {"mean": 5, "std": 2},
        "intelligence": {"mean": 7, "std": 2},
        "courage": {"mean": 4, "std": 2},
        "talkativeness": {"mean": 4, "std": 2},
        "extraversion": {"mean": 2, "std": 2},
        "patience": {"mean": 6, "std": 2},
        "empathy": {"mean": 5, "std": 2},
        "openness": {"mean": 4, "std": 2},
    },
    "spellwright": {
        "morality": {"mean": 5, "std": 2},
        "intelligence": {"mean": 7, "std": 2},
        "courage": {"mean": 5, "std": 2},
        "talkativeness": {"mean": 5, "std": 2},
        "extraversion": {"mean": 4, "std": 2},
        "patience": {"mean": 4, "std": 2},
        "empathy": {"mean": 4, "std": 2},
        "openness": {"mean": 5, "std": 2},
    },
    "smuggler": {
        "morality": {"mean": 4, "std": 2},
        "intelligence": {"mean": 5, "std": 2},
        "courage": {"mean": 6, "std": 2},
        "talkativeness": {"mean": 6, "std": 2},
        "extraversion": {"mean": 5, "std": 2},
        "patience": {"mean": 2, "std": 2},
        "empathy": {"mean": 2, "std": 2},
        "openness": {"mean": 1, "std": 2},
    },
    "khajiit_caravaneer": {
        "morality": {"mean": 5, "std": 2},
        "intelligence": {"mean": 5, "std": 2},
        "courage": {"mean": 5, "std": 2},
        "talkativeness": {"mean": 7, "std": 2},
        "extraversion": {"mean": 6, "std": 2},
        "patience": {"mean": 4, "std": 2},
        "empathy": {"mean": 4, "std": 2},
        "openness": {"mean": 5, "std": 2},
    },
    "argonian_slave": {
        "morality": {"mean": 6, "std": 2},
        "intelligence": {"mean": 4, "std": 2},
        "courage": {"mean": 4, "std": 2},
        "talkativeness": {"mean": 3, "std": 2},
        "extraversion": {"mean": 3, "std": 2},
        "patience": {"mean": 5, "std": 2},
        "empathy": {"mean": 5, "std": 2},
        "openness": {"mean": 3, "std": 2},
    },
}
