background_to_biography_facts_probabilities = {
    "commoner": {
        "poverty_stricken_childhood": 0.30,
        "skilled_artisan": 0.20,
        "streetwise_urchin": 0.20,
        "lost_family": 0.10,
        "mystical_encounter": 0.05,
        "secretive_past": 0.05,
        "rogueish_charm": 0.05,
        "natural_born_leader": 0.05,
    },
    "guard": {
        "former_mercenary": 0.30,
        "veteran_of_battles": 0.25,
        "natural_born_leader": 0.15,
        "affluent_upbringing": 0.10,
        "farmhand_turned_warrior": 0.10,
        "secret_lineage": 0.05,
        "mystical_encounter": 0.05,
    },
    "mage": {
        "gifted_apprentice": 0.30,
        "reclusive_scholar": 0.25,
        "mystical_encounter": 0.20,
        "failed_mage": 0.10,
        "botched_alchemy": 0.05,
        "whispered_prophecies": 0.05,
        "secretive_past": 0.05,
    },
    "necromancer": {
        "cursed_by_birth": 0.30,
        "reclusive_scholar": 0.25,
        "secretive_past": 0.20,
        "cult_escapee": 0.15,
        "disgraced_noble": 0.05,
        "mystical_encounter": 0.05,
    },
    "telvanni_mage": {
        "gifted_apprentice": 0.30,
        "reclusive_scholar": 0.25,
        "secretive_past": 0.20,
        "mystical_encounter": 0.10,
        "whispered_prophecies": 0.05,
        "affluent_upbringing": 0.05,
        "botched_alchemy": 0.05,
    },
    "noble": {
        "affluent_upbringing": 0.40,
        "disgraced_noble": 0.20,
        "mysterious_benefactor": 0.15,
        "secret_lineage": 0.10,
        "charismatic_diplomat": 0.10,
        "forgotten_royalty": 0.05,
    },
    "adventurer": {
        "lone_wanderer": 0.25,
        "daring_explorer": 0.20,
        "shipwreck_survivor": 0.15,
        "escaped_captivity": 0.10,
        "wandering_minstrel": 0.10,
        "natural_born_leader": 0.10,
        "illicit_treasure_hunter": 0.10,
    },
    "outlaw": {
        "streetwise_urchin": 0.25,
        "escaped_captivity": 0.20,
        "rogueish_charm": 0.15,
        "illicit_treasure_hunter": 0.15,
        "exiled_traitor": 0.10,
        "bounty_hunter": 0.10,
        "secretive_past": 0.05,
    },
    "hermit": {
        "hermitic_lifestyle": 0.40,
        "reclusive_scholar": 0.20,
        "secretive_past": 0.15,
        "mystical_encounter": 0.10,
        "lost_family": 0.10,
        "cursed_by_birth": 0.05,
    },
    "ashlander": {
        "orphaned_at_birth": 0.25,
        "lone_wanderer": 0.20,
        "natural_born_leader": 0.15,
        "lost_family": 0.15,
        "mystical_encounter": 0.10,
        "cult_escapee": 0.10,
        "hermitic_lifestyle": 0.05,
    },
    "sadrith_mora_scholar": {
        "reclusive_scholar": 0.30,
        "gifted_apprentice": 0.25,
        "mysterious_benefactor": 0.15,
        "failed_mage": 0.10,
        "secretive_past": 0.10,
        "whispered_prophecies": 0.10,
    },
    "redoran_warrior": {
        "farmhand_turned_warrior": 0.30,
        "veteran_of_battles": 0.25,
        "natural_born_leader": 0.15,
        "lost_family": 0.15,
        "affluent_upbringing": 0.10,
        "famed_duelist": 0.05,
    },
    "hlaalu_trader": {
        "streetwise_urchin": 0.25,
        "skilled_artisan": 0.20,
        "charismatic_diplomat": 0.15,
        "rogueish_charm": 0.15,
        "poverty_stricken_childhood": 0.10,
        "secretive_past": 0.10,
        "mysterious_benefactor": 0.05,
    },
    "balmora_citizen": {
        "poverty_stricken_childhood": 0.30,
        "skilled_artisan": 0.25,
        "streetwise_urchin": 0.20,
        "lost_family": 0.10,
        "mystical_encounter": 0.10,
        "secretive_past": 0.05,
    },
    "vivec_city_monk": {
        "religious_upbringing": 0.30,
        "mystical_encounter": 0.25,
        "gifted_apprentice": 0.15,
        "orphaned_at_birth": 0.10,
        "lost_family": 0.10,
        "whispered_prophecies": 0.10,
    },
    "imperial_legionnaire": {
        "veteran_of_battles": 0.30,
        "farmhand_turned_warrior": 0.20,
        "natural_born_leader": 0.15,
        "escaped_captivity": 0.15,
        "affluent_upbringing": 0.10,
        "famed_duelist": 0.10,
    },
    "dwemer_researcher": {
        "reclusive_scholar": 0.35,
        "mysterious_benefactor": 0.20,
        "gifted_apprentice": 0.15,
        "secretive_past": 0.10,
        "lost_family": 0.10,
        "inventor_of_gadgets": 0.10,
    },
    "morrowind_pilgrim": {
        "religious_upbringing": 0.30,
        "orphaned_at_birth": 0.20,
        "mystical_encounter": 0.20,
        "lost_family": 0.15,
        "natural_born_leader": 0.10,
        "whispered_prophecies": 0.05,
    },
    "ebony_mine_worker": {
        "poverty_stricken_childhood": 0.40,
        "skilled_artisan": 0.25,
        "escaped_captivity": 0.15,
        "streetwise_urchin": 0.10,
        "farmhand_turned_warrior": 0.10,
    },
    "daedra_worshipper": {
        "cursed_by_birth": 0.30,
        "mystical_encounter": 0.25,
        "cult_escapee": 0.20,
        "secretive_past": 0.15,
        "orphaned_at_birth": 0.10,
    },
    "vampire_hunter": {
        "escaped_captivity": 0.25,
        "lost_family": 0.20,
        "mystical_encounter": 0.20,
        "former_mercenary": 0.15,
        "bounty_hunter": 0.10,
        "cursed_by_birth": 0.10,
    },
    "buoyant_armiger": {
        "veteran_of_battles": 0.30,
        "natural_born_leader": 0.25,
        "affluent_upbringing": 0.15,
        "famed_duelist": 0.15,
        "religious_upbringing": 0.10,
        "secret_lineage": 0.05,
    },
    "silt_strider_operator": {
        "poverty_stricken_childhood": 0.35,
        "streetwise_urchin": 0.25,
        "lone_wanderer": 0.15,
        "rogueish_charm": 0.15,
        "escaped_captivity": 0.10,
    },
    "mournhold_royalty": {
        "affluent_upbringing": 0.40,
        "forgotten_royalty": 0.25,
        "charismatic_diplomat": 0.15,
        "secret_lineage": 0.10,
        "disgraced_noble": 0.10,
    },
    "fisherman": {
        "poverty_stricken_childhood": 0.30,
        "lone_wanderer": 0.20,
        "shipwreck_survivor": 0.20,
        "orphaned_at_birth": 0.15,
        "streetwise_urchin": 0.10,
        "natural_born_leader": 0.05,
    },
    "alchemist": {
        "gifted_apprentice": 0.30,
        "botched_alchemy": 0.25,
        "reclusive_scholar": 0.20,
        "mysterious_benefactor": 0.15,
        "secretive_past": 0.10,
    },
    "spellwright": {
        "gifted_apprentice": 0.35,
        "failed_mage": 0.25,
        "mystical_encounter": 0.20,
        "reclusive_scholar": 0.10,
        "secretive_past": 0.10,
    },
    "smuggler": {
        "streetwise_urchin": 0.30,
        "illicit_treasure_hunter": 0.25,
        "rogueish_charm": 0.20,
        "escaped_captivity": 0.15,
        "exiled_traitor": 0.10,
    },
    "khajiit_caravaneer": {
        "wandering_minstrel": 0.30,
        "lone_wanderer": 0.25,
        "streetwise_urchin": 0.20,
        "rogueish_charm": 0.15,
        "mystical_encounter": 0.10,
    },
    "argonian_slave": {
        "escaped_captivity": 0.40,
        "poverty_stricken_childhood": 0.30,
        "cursed_by_birth": 0.15,
        "orphaned_at_birth": 0.10,
        "streetwise_urchin": 0.05,
    },
}
