biography_fact_enum = {
    "orphaned_at_birth": "Orphaned at birth",
    "escaped_captivity": "Escaped captivity",
    "lone_wanderer": "Lone wanderer",
    "hermitic_lifestyle": "Hermitic lifestyle",
    "affluent_upbringing": "Affluent upbringing",
    "poverty_stricken_childhood": "Poverty-stricken childhood",
    "former_mercenary": "Former mercenary",
    "natural_born_leader": "Natural-born leader",
    "skilled_artisan": "Skilled artisan",
    "gifted_apprentice": "Gifted apprentice",
    "lost_family": "Lost family",
    "wandering_minstrel": "Wandering minstrel",
    "shipwreck_survivor": "Shipwreck survivor",
    "reclusive_scholar": "Reclusive scholar",
    "failed_mage": "Failed mage",
    "disgraced_noble": "Disgraced noble",
    "cursed_by_birth": "Cursed by birth",
    "secretive_past": "Secretive past",
    "streetwise_urchin": "Streetwise urchin",
    "mystical_encounter": "Mystical encounter",
    "exiled_traitor": "Exiled traitor",
    "farmhand_turned_warrior": "Farmhand turned warrior",
    "inventor_of_gadgets": "Inventor of gadgets",
    "bardic_poet": "Bardic poet",
    "hidden_talents": "Hidden talents",
    "daring_explorer": "Daring explorer",
    "illicit_treasure_hunter": "Illicit treasure hunter",
    "mythic_visions": "Mythic visions",
    "cult_escapee": "Cult escapee",
    "rogueish_charm": "Rogueish charm",
    "bounty_hunter": "Bounty hunter",
    "whispered_prophecies": "Whispered prophecies",
    "reluctant_hero": "Reluctant hero",
    "forgotten_royalty": "Forgotten royalty",
    "charismatic_diplomat": "Charismatic diplomat",
    "famed_duelist": "Famed duelist",
    "botched_alchemy": "Botched alchemy",
    "mysterious_benefactor": "Mysterious benefactor",
    "veteran_of_battles": "Veteran of battles",
    "secret_lineage": "Secret lineage"
}
