class_enum = {
    "warrior": "Warrior",
    "mage": "Mage",
    "thief": "Thief",
    "monk": "Monk",
    "assassin": "Assassin",
    "bard": "Bard",
    "battlemage": "Battlemage",
    "crusader": "Crusader",
    "knight": "Knight",
    "pilgrim": "Pilgrim", 
    "scout": "Scout",
    "sorcerer": "Sorcerer",
    "spellsword": "Spellsword",
    "agent": "Agent",
    "archer": "Archer",
    "healer": "Healer",
    "rogue": "Rogue",
    "witchhunter": "Witchhunter",
}
