location_type_enum = {
    "village": "Village",
    "fortified_settlement": "Fortified Settlement",
    "town": "Town",
    "mining_town": "Mining Town",
    "city": "City",
    "grand_city": "Grand City",
    "kwama_egg_mine": "Kwama Egg Mine",
    "imperial_fort": "Imperial Fort",
    "daedric_shrine": "Daedric Shrine",
    "dunmer_stronghold": "Dunmer Stronghold",
    "cave": "Cave",
    "telvanni_mage_tower": "Telvanni Mage Tower",
    "ashlander_camp": "Ashlander Camp",
    "dwemer_ruin": "Dwemer Ruin",
    "silt_strider_port": "Silt Strider Port",
    "nordic_ruin": "Nordic Ruin",
    "fishing_village": "Fishing Village",
    "farmstead": "Farmstead",
    "alchemy_shop": "Alchemy Shop",
    "tavern": "Tavern",
    "marketplace": "Marketplace",
    "guild_hall": "Guild Hall",
    "temple": "Temple",
    "hermit_abode": "Hermit's Abode",
    "bandit_camp": "Bandit Camp",
    "ghost_town": "Ghost Town",
    "graveyard": "Graveyard",
    "ancient_monument": "Ancient Monument",
    "slave_plantation": "Slave Plantation",
    "hunters_camp": "Hunter's Camp",
    "imperial_trading_post": "Imperial Trading Post",
    "velothi_tower": "Velothi Tower",
    "lighthouse": "Lighthouse",
    "magistrate_office": "Magistrate's Office",
    "shipwreck": "Shipwreck"
}
