from enum import Enum

class quality_enum(Enum):
    SHORT = "short"
    LONG = "long"
    IRON = "iron"
    STEEL = "steel"
    SILVER = "silver"
    ELVEN = "elven"
    GLASS = "glass"
    DWARWEN = "dwarwen"
    ORCISH = "orcish"
    EBONY = "ebony"
    DAEDRIC = "daedric"
    LEATHER = "leather"
    NETCH_LEATHER = "netch_leather"
    LESSER = "lesser"
    SMALL = "small"
    BIG = "big"
    CHEAP = "cheap"
    BLACK = "black"
    CHITIN = "chitin"
    BONEMOLD = "bonemold"
    ADAMANTIUM = "adamantium"
    STALHRIM = "stalhrim"
    IMPERIAL = "imperial"
    NORDIC = "nordic"
    DRUEGHA = "dreugh"
    INDORIL = "indoril"
    COMMON = "common"
    EXQUISITE = "exquisite"
    EXTRAVAGANT = "extravagant"
    ENCHANTED = "enchanted"