from enum import Enum

class ReligionEnum(Enum):
    NINE_D = "Nine Divines"
    ALDMERI_P = "Aldmeri Pantheon"
    REDGUARD_P = "Redguard Pantheon"
    TRIBUNAL_T = "Tribunal Temple"
    IMPERIAL_CULT = "Imperial Cult"
    HIST = "Hist"
    ASHLANDER = "Ashlander Cults"
    AZURA = "Azura"
    BOETHIAH = "Boethiah"
    CLAVICUS_VILE = "Clavicus Vile"
    HERMAEUS_MORA = "Hermaeus Mora"
    HIRCINE = "Hircine"
    MALACATH = "Malacath"
    MEHRUNES_DAGON = "Mehrunes Dagon"
    MEPHALA = "Mephala"
    MERIDIA = "Meridia"
    MOLAG_BAL = "Molag Bal"
    NAMIRA = "Namira"
    NOCTURNAL = "Nocturnal"
    PERYITE = "Peryite"
    SANGUINE = "Sanguine"
    SHEOGORATH = "Sheogorath"
    VAERMINA = "Vaermina"
