from enum import Enum

class SkillEnum(Enum):
    ALCHEMY = "Alchemy"
    ATHLETICS = "Athletics"
    BLOCK = "Block"
    ARMORER = "Armorer"
    LIGHT_ARMOR = "Light Armor"
    MEDIUM_ARMOR = "Medium Armor"
    HEAVY_ARMOR = "Heavy Armor"
    BLUNT_WEAPON = "Blunt Weapon"
    SHORT_BLADE = "Short Blade"
    LONG_BLADE = "Long Blade"
    AXE = "Axe"
    SPEAR = "Spear"
    DESTRUCTION = "Destruction"
    ALTERATION = "Alteration"
    ILLUSION = "Illusion"
    CONJURATION = "Conjuration"
    MYSTICISM = "Mysticism"
    RESTORATION = "Restoration"
    ENCHANT = "Enchant"
    SECURITY = "Security"
    SNEAK = "Sneak"
    ACROBATICS = "Acrobatics"
    MARKSMAN = "Marksman"
    MERCANTILE = "Mercantile"
    SPEECHCRAFT = "Speechcraft"
    HAND_TO_HAND = "Hand-to-hand"
