skill_enum = {
    "alchemy": "Alchemy",
    "athletics": "Athletics",
    "block": "Block",
    "armorer": "Armorer",
    "light_armor": "Light Armor",
    "medium_armor": "Medium Armor",
    "heavy_armor": "Heavy Armor",
    "blunt_weapon": "Blunt Weapon",
    "short_blade": "Short Blade",
    "long_blade": "Long Blade",
    "axe": "Axe",
    "spear": "Spear",
    "destruction": "Destruction",
    "alteration": "Alteration",
    "illusion": "Illusion",
    "conjuration": "Conjuration",
    "mysticism": "Mysticism",
    "restoration": "Restoration",
    "enchant": "Enchant",
    "security": "Security",
    "sneak": "Sneak",
    "acrobatics": "Acrobatics",
    "marksman": "Marksman",
    "mercantile": "Mercantile",
    "speechcraft": "Speechcraft",
    "hand_to_hand": "Hand-to-hand"
}
