from enum import Enum

class SpellEnum(Enum):
    FIREBALL = "fireball"
    FROSTBITE = "frostbite"
    LEVITATION = "levitation"
    SUMMON_SCAMP = "summon_scamp"
    HEAL = "heal"
    NIGHT_EYE = "night_eye"
    BOUND_SWORD = "bound_sword"
    WATER_BREATHING = "water_breathing"
    PARALYSIS = "paralysis"
    CHAMELEON = "chameleon"
    BOUND_BOW = "bound_bow"
    SUMMON_SKELETON = "summon_skeleton"
    CURE_COMMON_DISEASE = "cure_common_disease"
    DETECT_CREATURE = "detect_creature"
    DISPEL = "dispel"
    FIRE_SHIELD = "fire_shield"
    FROST_SHIELD = "frost_shield"
    LIGHTNING_SHIELD = "lightning_shield"
    MARK = "mark"
    RECALL = "recall"
    TELEKINESIS = "telekinesis"
    WATER_WALKING = "water_walking"
    FORTIFY_ATTRIBUTE = "fortify_attribute"
    FORTIFY_SKILL = "fortify_skill"
