
spell_enum = {
    "fireball": "Fireball",
    "heal": "Heal",
    "invisibility": "Invisibility",
    "levitation": "Levitation",
    "frostbite": "Frostbite",
    "summon_scamp": "Summon Scamp",
    "night_eye": "Night Eye",
    "bound_sword": "Bound Sword",
    "water_breathing": "Water Breathing",
    "paralysis": "Paralysis",
    "chameleon": "Chameleon",
    "shield": "Shield",
    "bound_bow": "Bound Bow",
    "summon_skeleton": "Summon Skeleton",
    "cure_common_disease": "Cure Common Disease",
    "detect_creature": "Detect Creature",
    "dispel": "Dispel",
    "fire_shield": "Fire Shield",
    "frost_shield": "Frost Shield",
    "lightning_shield": "Lightning Shield",
    "mark": "Mark",
    "recall": "Recall",
    "telekinesis": "Telekinesis",
    "water_walking": "Water Walking",
    "fortify_attribute": "Fortify Attribute",
    "fortify_skill": "Fortify Skill",
    "absorb_health": "Absorb Health",
    "absorb_magicka": "Absorb Magicka",
    "reflect": "Reflect",
    "cure_poison": "Cure Poison",
    "cure_blight_disease": "Cure Blight Disease",
    "restore_attribute": "Restore Attribute",
    "restore_health": "Restore Health",
    "restore_magicka": "Restore Magicka",
    "restore_fatigue": "Restore Fatigue",
    "resist_fire": "Resist Fire",
    "resist_frost": "Resist Frost",
    "resist_shock": "Resist Shock",
    "resist_magicka": "Resist Magicka",
    "resist_poison": "Resist Poison",
    "resist_common_disease": "Resist Common Disease",
    "resist_blight_disease": "Resist Blight Disease",
    "resist_paralysis": "Resist Paralysis",
    "resist_corprus": "Resist Corprus",
    # ... Additional spells can be added as needed
}
