import templates.profiles.profiles as prof

balmora_pop_config = [
    {"profile": prof.balmora_citizen, "probability": 0.35},
    {"profile": prof.commoner_hlaalu, "probability": 0.15},
    {"profile": prof.commoner_redoran, "probability": 0.05},
    {"profile": prof.commoner_telvanni, "probability": 0.03},
    {"profile": prof.commoner_imperial, "probability": 0.08},
    {"profile": prof.commoner_argonian, "probability": 0.04},
    {"profile": prof.commoner_khajiit, "probability": 0.03},
    {"profile": prof.commoner_nord, "probability": 0.03},
    {"profile": prof.commoner_breton, "probability": 0.02},
    {"profile": prof.commoner_orc, "probability": 0.02},
    {"profile": prof.commoner_redguard, "probability": 0.02},
    {"profile": prof.commoner_wood_elf, "probability": 0.01},
    {"profile": prof.commoner_high_elf, "probability": 0.01},
    {"profile": prof.guard_hlaalu, "probability": 0.04},
    {"profile": prof.guard_imperial, "probability": 0.02},
    {"profile": prof.mage_breton, "probability": 0.01},
    {"profile": prof.mage_high_elf, "probability": 0.01},
    {"profile": prof.hlaalu_trader, "probability": 0.02},
    {"profile": prof.smuggler_dark_elf, "probability": 0.02},
    {"profile": prof.merchant_imperial, "probability": 0.02},
    {"profile": prof.farmer_hlaalu, "probability": 0.02},
    {"profile": prof.silt_strider_operator, "probability": 0.01},
    {"profile": prof.dwemer_researcher, "probability": 0.01},
    {"profile": prof.ashlander, "probability": 0.01},
    {"profile": prof.alchemist, "probability": 0.01},
    {"profile": prof.spellwright, "probability": 0.01},
    {"profile": prof.vivec_city_monk, "probability": 0.01},
    {"profile": prof.outlaw_dark_elf_hlaalu, "probability": 0.01},
    {"profile": prof.kwama_egg_miner, "probability": 0.01},
]