from enum import Enum


class PotionEnum(Enum):
    SMALL_RESTORE_HEALTH = "small_restore_health_potion"
    MEDIUM_RESTORE_HEALTH = "medium_restore_health_potion"
    LARGE_RESTORE_HEALTH = "large_restore_health_potion"
    SMALL_FORTIFY_STRENGTH = "small_fortify_strength_potion"
    MEDIUM_FORTIFY_STRENGTH = "medium_fortify_strength_potion"
    LARGE_FORTIFY_STRENGTH = "large_fortify_strength_potion"
    SMALL_RESTORE_MAGICKA = "small_restore_magicka_potion"
    MEDIUM_RESTORE_MAGICKA = "medium_restore_magicka_potion"
    LARGE_RESTORE_MAGICKA = "large_restore_magicka_potion"
    SMALL_INVISIBILITY = "small_invisibility_potion"
    MEDIUM_INVISIBILITY = "medium_invisibility_potion"
    LARGE_INVISIBILITY = "large_invisibility_potion"
    SMALL_FORTIFY_UNARMORED = "small_fortify_unarmored_potion"
    MEDIUM_FORTIFY_UNARMORED = "medium_fortify_unarmored_potion"
    LARGE_FORTIFY_UNARMORED = "large_fortify_unarmored_potion"
    SMALL_POISON = "small_poison_potion"
    MEDIUM_POISON = "medium_poison_potion"
    LARGE_POISON = "large_poison_potion"
    SMALL_SWIFT_SWIM = "small_swift_swim_potion"
    MEDIUM_SWIFT_SWIM = "medium_swift_swim_potion"
    LARGE_SWIFT_SWIM = "large_swift_swim_potion"
    SMALL_FORTIFY_PERSONALITY = "small_fortify_personality_potion"
    MEDIUM_FORTIFY_PERSONALITY = "medium_fortify_personality_potion"
    LARGE_FORTIFY_PERSONALITY = "large_fortify_personality_potion"
    SMALL_FORTIFY_ATTACK = "small_fortify_attack_potion"
    MEDIUM_FORTIFY_ATTACK = "medium_fortify_attack_potion"
    LARGE_FORTIFY_ATTACK = "large_fortify_attack_potion"
    SMALL_FORTIFY_ENDURANCE = "small_fortify_endurance_potion"
    MEDIUM_FORTIFY_ENDURANCE = "medium_fortify_endurance_potion"
    LARGE_FORTIFY_ENDURANCE = "large_fortify_endurance_potion"
    SMALL_RESTORE_FATIGUE = "small_restore_fatigue_potion"
    MEDIUM_RESTORE_FATIGUE = "medium_restore_fatigue_potion"
    LARGE_RESTORE_FATIGUE = "large_restore_fatigue_potion"
    SMALL_CHAMELEON = "small_chameleon_potion"
    MEDIUM_CHAMELEON = "medium_chameleon_potion"
    LARGE_CHAMELEON = "large_chameleon_potion"
    SMALL_FORTIFY_AGILITY = "small_fortify_agility_potion"
    MEDIUM_FORTIFY_AGILITY = "medium_fortify_agility_potion"
    LARGE_FORTIFY_AGILITY = "large_fortify_agility_potion"
    SMALL_CURE_COMMON_DISEASE = "small_cure_common_disease_potion"
    MEDIUM_CURE_COMMON_DISEASE = "medium_cure_common_disease_potion"
    LARGE_CURE_COMMON_DISEASE = "large_cure_common_disease_potion"
    SMALL_BLESSED_WATER = "small_blessed_water_potion"
    MEDIUM_BLESSED_WATER = "medium_blessed_water_potion"
    LARGE_BLESSED_WATER = "large_blessed_water_potion"

