from enum import Enum


class SpellBookEnum(Enum):
    """
    This enum represents the different types of spell books available in the game.
    """
    TOME_OF_FIREBALL = "tome_of_fireball"
    TOME_OF_FROSTBITE = "tome_of_frostbite"
    TOME_OF_LEVITATION = "tome_of_levitation"
    TOME_OF_SUMMON_SCAMP = "tome_of_summon_scamp"
    TOME_OF_HEAL = "tome_of_heal"
    TOME_OF_NIGHT_EYE = "tome_of_night_eye"
    TOME_OF_BOUND_SWORD = "tome_of_bound_sword"
    TOME_OF_WATER_BREATHING = "tome_of_water_breathing"
    TOME_OF_PARALYSIS = "tome_of_paralysis"
    TOME_OF_CHAMELEON = "tome_of_chameleon"
    TOME_OF_BOUND_BOW = "tome_of_bound_bow"
    TOME_OF_SUMMON_SKELETON = "tome_of_summon_skeleton"
    TOME_OF_CURE_COMMON_DISEASE = "tome_of_cure_common_disease"
    TOME_OF_DETECT_CREATURE = "tome_of_detect_creature"
    TOME_OF_DISPEL = "tome_of_dispel"
    TOME_OF_FIRE_SHIELD = "tome_of_fire_shield"
    TOME_OF_FROST_SHIELD = "tome_of_frost_shield"
    TOME_OF_LIGHTNING_SHIELD = "tome_of_lightning_shield"
    TOME_OF_MARK = "tome_of_mark"
    TOME_OF_RECALL = "tome_of_recall"
    TOME_OF_TELEKINESIS = "tome_of_telekinesis"
    TOME_OF_WATER_WALKING = "tome_of_water_walking"
    TOME_OF_FORTIFY_STRENGTH = "tome_of_fortify_strength"
    TOME_OF_FORTIFY_INTELLIGENCE = "tome_of_fortify_intelligence"
    TOME_OF_FORTIFY_WILLPOWER = "tome_of_fortify_willpower"
    TOME_OF_FORTIFY_AGILITY = "tome_of_fortify_agility"
    TOME_OF_FORTIFY_SPEED = "tome_of_fortify_speed"
    TOME_OF_FORTIFY_ENDURANCE = "tome_of_fortify_endurance"
    TOME_OF_FORTIFY_PERSONALITY = "tome_of_fortify_personality"
    TOME_OF_FORTIFY_LUCK = "tome_of_fortify_luck"
    TOME_OF_FORTIFY_LONG_BLADE = "tome_of_fortify_long_blade"
    TOME_OF_FORTIFY_SHORT_BLADE = "tome_of_fortify_short_blade"
    TOME_OF_FORTIFY_LIGHT_ARMOR = "tome_of_fortify_light_armor"
    TOME_OF_FORTIFY_HEAVY_ARMOR = "tome_of_fortify_heavy_armor"
    TOME_OF_FORTIFY_BLOCK = "tome_of_fortify_block"
    TOME_OF_FORTIFY_AXE = "tome_of_fortify_axe"
    TOME_OF_FORTIFY_BOW = "tome_of_fortify_bow"
    TOME_OF_FORTIFY_SPEAR = "tome_of_fortify_spear"
    TOME_OF_FORTIFY_ARMORER = "tome_of_fortify_armorer"
    TOME_OF_FORTIFY_DESTRUCTION = "tome_of_fortify_destruction"
    TOME_OF_FORTIFY_ALTERATION = "tome_of_fortify_alteration"
    TOME_OF_FORTIFY_ILLUSION = "tome_of_fortify_illusion"
    TOME_OF_FORTIFY_CONJURATION = "tome_of_fortify_conjuration"
    TOME_OF_FORTIFY_MYSTICISM = "tome_of_fortify_mysticism"
    TOME_OF_FORTIFY_ENCHANT = "tome_of_fortify_enchant"
    TOME_OF_FORTIFY_RESTORATION = "tome_of_fortify_restoration"
    TOME_OF_FORTIFY_ALCHEMY = "tome_of_fortify_alchemy"
    TOME_OF_FORTIFY_UNARMORED = "tome_of_fortify_unarmored"
    TOME_OF_FORTIFY_SECURITY = "tome_of_fortify_security"
    TOME_OF_FORTIFY_SNEAK = "tome_of_fortify_sneak"
    TOME_OF_FORTIFY_ACROBATICS = "tome_of_fortify_acrobatics"
